package sqlm

import (
	"context"
	"fmt"
)

// ExecAndLastInsertID executes a prepared statement with the given arguments and
// returns the integer generated by the database in response to a command.
// Typically, this will be from an "auto increment" column when inserting a new row.
// Not all databases support this feature, and the syntax of such statements varies.
func ExecAndLastInsertID(ctx context.Context, conn Tx, query string, args ...any) (id int64, err error) {
	rs, err := conn.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("query executing: %w", err)
	}
	return rs.LastInsertId()
}

// ExecAndRowsAffected executes a prepared statement with the given arguments and
// returns the number of rows affected by an update, insert, or delete.
// Not every database or database driver may support this.
func ExecAndRowsAffected(ctx context.Context, conn Tx, query string, args ...any) (id int64, err error) {
	rs, err := conn.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("query executing: %w", err)
	}
	return rs.RowsAffected()
}
